### PR TITLE
Use motion_imitation in third parties libraries

### PR DESCRIPTION
**Pull request by nicrusso7**
This PR proposes a way to integrate `motion_imitation` in third parties libraries. 
I've removed the hardcoded `robot_class` variable in the `env_builder` script and I've defined a `SimpleRobotOffsetGenerator`.

With these changes, the integration in third parties libraries can be made as follows:
```
env = env_builder.build_imitation_env(motion_files=["trot2.txt"],
                                      num_parallel_envs=1,
                                      mode="train",
                                      enable_randomizer=True,
                                      enable_rendering=True,
                                      robot_class=my_robot.MyRobot,
                                      trajectory_generator=simple_openloop.SimpleRobotOffsetGenerator(
                                      action_limit=6.28318548203, pose=myrobot_constants.INIT_JOINT_ANGLES_ARRAY)) 
model = build_model(env=env,
                    num_procs=1,
                    timesteps_per_actorbatch=4096,
                    optim_batchsize=256,
                    output_dir="output")

train(model=model,
      env=env,
      total_timesteps=2e8,
      output_dir="output",
      int_save_freq=10000000)
```
This changes also prepare the field for adding a `--robot` parameter in the `run` script to switch between laikago and a1 (or any other future robot).

This PR also edits the `retarget_motion` script in order to use the mocap filename as output filename.

### CODE REVIEW

**Comment by nicrusso7** [comment]
@googlebot I signed it!

**Comment by erwincoumans** [comment]
Thanks for the contribution, somehow I haven't seen the pull request (there are no real resources for support).
At a first glance it looks fine, but it needs a bit more testing to make sure it doesn't break anything.

**Comment by nicrusso7** [comment]
Thanks @erwincoumans, happy to address any comment/issue. I will also test next weekend (I see there are some updates since I've opened this PR).

**Comment by nicrusso7** [comment]
Hi @erwincoumans, I've merged the master from upstream and I've tested launching a training session (single and multi-threads) and visualizing the trained model that is already in the repository. No issue at all. I'll waiting your tests as well! thanks!

**Comment by nicrusso7** [comment]
I can also confirms that `locomotion_controller_example.py` works good meanwhile the `whole_body_controller_example.py` just terminate with this logs:

`pybullet build time: Oct  8 2020 00:10:46`
`I1208 15:12:02.944559 140454249850688 openloop_gait_generator.py:189] lost contact detected.
` 

however this happen to me also using the original repository code. Waiting for your tests!

Thank you.

**Comment by erwincoumans** [comment]
That is expected, you need to use the flags --show_gui to have display for the whole_body_controller_example (and --max_time_secs=10 or so)

**Comment by nicrusso7** [comment]
Correct, sorry about that. I can confirm the `whole_body_controller_example.py` works good!

**Comment by nicrusso7** [comment]
Hi @erwincoumans, please let me know if I can do something else for this PR!

**Comment by erwincoumans** [comment]
Excuses for the delay, let's merge it.

**Comment by nicrusso7** [comment]
awesome, thank you!

**Pull request merged**
